services:
  - type: web
    name: inventory-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_COOKIE_SECURE
        value: "True"
      - key: FLASK_COOKIE_HTTPONLY
        value: "True"
      - key: GUNICORN_WORKERS
        value: "4"
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true 